param(
    [string]$MySqlPath = "C:\Program Files\MySQL\MySQL Server 8.4\bin\mysql.exe"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$projectRoot = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $projectRoot ".env"

if (-not (Test-Path -LiteralPath $MySqlPath)) {
    throw "MySQL client not found: $MySqlPath"
}

function New-RandomHex([int]$byteCount) {
    $bytes = New-Object byte[] $byteCount
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($bytes)
    }
    finally {
        $rng.Dispose()
    }
    return -join ($bytes | ForEach-Object { $_.ToString("x2") })
}

$databaseName = "resume_assistant"
$databaseUser = "resume_app"
$databasePassword = New-RandomHex 24
$jwtSecret = New-RandomHex 32
$adminPassword = New-RandomHex 12

$sql = @"
CREATE DATABASE IF NOT EXISTS $databaseName
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS '$databaseUser'@'127.0.0.1' IDENTIFIED BY '$databasePassword';
ALTER USER '$databaseUser'@'127.0.0.1' IDENTIFIED BY '$databasePassword';
GRANT ALL PRIVILEGES ON $databaseName.* TO '$databaseUser'@'127.0.0.1';
"@

$sql | & $MySqlPath --protocol=TCP -h 127.0.0.1 -P 3306 -u root
if ($LASTEXITCODE -ne 0) {
    throw "MySQL bootstrap failed with exit code $LASTEXITCODE"
}

$envContent = @"
# Local-only configuration generated by scripts/bootstrap_local.ps1
JWT_SECRET_KEY=$jwtSecret
ADMIN_EMAIL=admin@localhost
ADMIN_PASSWORD=$adminPassword

LLM_API_KEY=
BASE_URL=
LLM_MODEL=gemini-3-flash-preview
TAVILY_API_KEY=

DATABASE_URL=mysql+pymysql://$databaseUser`:$databasePassword@127.0.0.1:3306/$databaseName`?charset=utf8mb4

HOST=127.0.0.1
PORT=8000
DOMAIN=localhost
WEASYPRINT_DLL_DIRECTORIES=C:\resume-tools\msys64\ucrt64\bin
"@

[System.IO.File]::WriteAllText(
    $envPath,
    $envContent,
    (New-Object System.Text.UTF8Encoding($false))
)

Write-Output "Local MySQL database and .env were created successfully."
Write-Output "Secrets were written only to the ignored .env file and were not printed."
